### ISSUE TITLE
Transaction処理について

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/Categories#13]
https://github.com/NetCommons3/ContentComments/issues/18

**Comment by s-nakajima** [comment]
BehaviorのbeforeSaveに移動したことで、呼び出し元でTransactionを開始することになったため、Closeする

https://github.com/NetCommons3/Categories/commit/0c67ea74a5397bb4055ccb1818eb263c9139ba18#diff-c880fcb4b81cc2b68efdbc2a8b43f345
